### ISSUE TITLE
Activation Functions tf.maximum

### ISSUE THREAD

**Issue by kopytjuk** [anoff/deep-emoji-gan#8]
Why do you use tf.maximum(conv, conv*alpha) as an activation function - try to use ReLU (tf.nn.relu) instead! It should help!

The next problem was scaling - the pictures you took were already scaled to 0, 1 :)) working version here:
[https://github.com/kopytjuk/deep-emoji-gan/blob/master/Smiley_Generator.ipynb](url)

**Comment by anoff** [comment]
It's a leaky ReLU
